version: '2'
services:
  full-node:
    build:
      context: ../
    volumes:
        - ./docker_files/genesis.json:/genesis.json:ro
        - ./docker_files/run.sh:/run.sh:ro
    entrypoint: /run.sh full-node
    environment:
      - PRIVATE_KEY=896d9877772a76c6d331f3d3c28f84331c2349dc817c682dc0b816107bff3b6c # 0x038FE564172439aB9EdCD492C8e886A26be99b3d
      - ETHERBASE=0x038FE564172439aB9EdCD492C8e886A26be99b3d
#  proposer:
#    build:
#      context: ../
#    entrypoint: geth --help
  collator:
    build:
      context: ../
    environment:
      - PRIVATE_KEY=896d9877772a76c6d331f3d3c28f84331c2349dc817c682dc0b816107bff3b6c # 0x038FE564172439aB9EdCD492C8e886A26be99b3d
      - ETHERBASE=0x038FE564172439aB9EdCD492C8e886A26be99b3d
    volumes:
        - ./docker_files/genesis.json:/genesis.json:ro
        - ./docker_files/run.sh:/run.sh:ro
    entrypoint: /run.sh collator
